github: jodastephen
open_collective: joda
tidelift: maven/org.joda:joda-money

# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
