open_collective: joda
tidelift: maven/org.joda:joda-money

# github: [jodastephen]
# patreon: # Replace with a single Patreon username
# ko_fi: # Replace with a single Ko-fi username
# custom: # Replace with a single custom sponsorship URL
